#https://docs.docker.com/compose/
networks:
  default:
    external: true
    name: ${NETWORK_NAME:-selenoid}

services:
#  selenoid:
#    image: aerokube/selenoid:latest-release
#    volumes:
#      - "./config:/etc/selenoid"
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "${NETWORK_NAME:-selenoid}" ]
#    healthcheck:
#      test: [ "CMD", "curl", "localhost:4444/ping" ]

#  percona:
#    tty: true
#    environment:
#      MYSQL_ROOT_PASSWORD: pass
#    image: "percona:latest"
#    healthcheck:
#      test: ["CMD", "mysqladmin", "-uroot", "-ppass", "ping", "-h", "percona"]
#      timeout: 1s
#      retries: 30

  tests:
    tty: true
    build: .
    volumes:
      - ./:/main
      - ./tmp:/tmp
    command: ["/main/run.sh", "api"]
#    command: ["/main/run.sh", "ui", "-m", "debug", "--url=http://devdivision.io", "--selenoid"]
#    depends_on:
#      percona:
#        condition: service_healthy
